# Generated by Django 4.2 on 2023-05-01 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_room_paticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='paticipants',
            field=models.ManyToManyField(blank=True, related_name='paticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
